---
- name: Apply STIG and run SCAP scans on Rocky Linux
  hosts: rocky9_target   # â† change to your inventory group/host
  become: yes

  tasks:

    - name: Ensure SSG and OpenSCAP are installed
      package:
        name:
          - scap-security-guide
          - openscap-scanner
        state: present

    - name: Generate DISA STIG remediation script
      command: >
        oscap xccdf generate fix
          --profile xccdf_org.ssgproject.content_profile_stig
          --output /root/stig-fix.sh
          /usr/share/xml/scap/ssg/content/ssg-rockylinux9-ds.xml
      args:
        creates: /root/stig-fix.sh

    - name: Apply STIG remediation
      command: bash /root/stig-fix.sh

    - name: Perform OpenSCAP evaluation and generate reports
      command: >
        oscap xccdf eval
          --profile xccdf_org.ssgproject.content_profile_stig
          --report /root/openscap-report.html
          --results /root/openscap-results.xml
          /usr/share/xml/scap/ssg/content/ssg-rockylinux9-ds.xml
